### PR TITLE
Soft bed regions v2

### PR DESCRIPTION
**Pull request by bnoyvert**
The new `truvari bench` option `--extend` extends the regions of interest (set in `--includebed` argument) by the given number of bases on each side, allowing truth set variants to match call set variants that are just outside of the original region. If a call set variant is in the extended regions it can potentially match a truth set variant that is in the original regions turning it to TP, but call set variants in the extended regions that don't have a match are not counted as FP. This strategy is similar to the one implemented in `truvari bench` for size matching - only the truth set variants longer than `sizemin` (equal to 50 by default) are considered, but they are allowed to match shorter comparison set variants of size `sizefilt` (30 by default) or longer.

The default is `--extend 0` - no extension, producing the same results as previous versions of `truvari bench`. 

See the following [discussion ](https://github.com/ACEnglish/truvari/discussions/99) for details.

### CODE REVIEW

**Review by ACEnglish — APPROVED** [review]
Looks good. I'm going to change the version back to 3.3.0-dev because we haven't released 3.3, yet. I'll also be shortening the description of the new parameter. I'm probably going to pull most of lines 796:806 to somewhere outside of main as well as probably 814 (that's a long if, might give it a method).

**Comment by ACEnglish** [comment]
FYI, I made some style changes in 9e4e8a8. Functests all pass.

**Comment by bnoyvert** [comment]
Thank you, this is all fine.
Just being paranoid - what happens to `regions_extended = regions.extend(args.extend) if args.extend else regions` if args.extend is a negative number? Would it be safer to put `if args.extend > 0`?

**Comment by bnoyvert** [comment]
Agree, argparse type requirement is probably the best.

**Comment by ACEnglish** [comment]
See 2f5b001

**Comment by bnoyvert** [comment]
Just noticed: in bench.py [line 647](https://github.com/ACEnglish/truvari/blob/87b40b11d69b47fc744c1ab3cbb0e3185a596960/truvari/bench.py#L647)
`    thresg.add_argument("--extend", type=truvari.restricted_int, default=0,`
should be `filteg.add_argument`. Sorry, my mistake.

**Comment by ACEnglish** [comment]
It's been changed. I appreciate you double/triple/+ checking. I'm very happy to add your work to the tool. Thanks so much for your contribution!!

**Pull request merged**
